### PR TITLE
Update setup configuration, CI, etc.

### PR DESCRIPTION
**Pull request by benbovy**
- Move back from poetry to a bare `setup.py` (easier to handle with conda)
- Use `setuptools_scm` for versioning 
- Configure pre-commit (I've recently started using it in other projects and I'm quite happy with it -- no more "fix black" like commits)
- Update github actions (lint + test)

### CODE REVIEW

**Comment by benbovy** [comment]
@willirath thanks for activating codecov for the org. I think it will be clearer to have one extra check for coverage instead of triggering test failures. If you can activate builds for pull-requests on readthedocs (in advanced settings), that would be great too!

Let me know if you have any objection regarding the choices made here (e.g., max line length, string delimiters, etc.). Otherwise, I'm going to merge this soon and move on with adding more index wrappers (scipy, pys2index, etc.).

**Comment by willirath** [comment]
@benbovy What’s your user on readthedocs? I’d like to also add you as maintainer there.

**Comment by willirath** [comment]
building PRs was already enabled.

**Comment by benbovy** [comment]
> @benbovy What’s your user on readthedocs? I’d like to also add you as maintainer there.

`girpas-ulg` (the name is because I created it some years ago at my previous work, but I'm the only user).

**Comment by willirath** [comment]
Added you on rtd.

**Comment by willirath** [comment]
> Let me know if you have any objection regarding the choices made here (e.g., max line length, string delimiters, etc.). Otherwise, I'm going to merge this soon and move on with adding more index wrappers (scipy, pys2index, etc.).

Configs look good to me. Feel free to merge whenever it suits you.

**Comment by benbovy** [comment]
Great, thanks.

**Pull request merged**
