### PR TITLE
Add more index adapters

### PR DESCRIPTION
**Pull request by benbovy**
TODO:

- [x] rename 'balltree' and 'geo_balltree' to 'sklearn_balltree' and 'sklearn_geo_balltree'
- [x] add `sklearn.neighbors.KDTree` adapter
- [x] add 's2point' index adapter (based on `pys2index`)
- [x] add `scipy.cKDTree` adapter

Maybe in this PR or later (if relevant):

- add "geo" kd-tree adapters (conversion from lat/lon to x/y/z)
- add [pykdtree](https://github.com/storpipfugl/pykdtree) adapters
- add [pyinterp](https://github.com/CNES/pangeo-pyinterp) adapters
- add [rtree](https://github.com/Toblerity/rtree) adapters

All dependencies are optional, adapters are not registered if their corresponding package is not installed.

### CODE REVIEW

**Comment by benbovy** [comment]
Each index adapter is tested against brute-force nearest neighbor lookup for the whole matrix:

- numpy/dask
- 1/2/3 dimension dataset coordinates
- 1/2/3 dimension indexer coordinates

Not sure we need to apply the whole matrix each time, but this can be addressed later.

**Comment by willirath** [comment]
Looks very good!

Two things I noticed:

1. We should list `scipy` as an explicit dependency (in the tests and in the env file) even if it is probably pulled by sklearn anyway.
2. The RTD build for this PR https://xoak--28.org.readthedocs.build/en/28/search.html?q=ScipyKDTreeAdapter&check_keywords=yes&area=default# doesn't seem to contain the S2 adapter. But maybe this is a caching issue.

**Comment by benbovy** [comment]
Good catch, your two points are addressed in the last commits.

I also implemented attribute access for the index registry. It's convenient for easily accessing the index adapter docstrings, e.g.,

```
In [1]: import xoak

In [2]: ireg = xoak.IndexRegistry()

In [3]: ireg.s2point?
Init signature: ireg.s2point(**kwargs)
Docstring:     
Xoak index adapter for :class:`pys2index.S2PointIndex`.

It can be used for efficient indexing of a set of latitude / longitude points.

When building the index, the coordinates must be given in the latitude,
longitude order.

Latitude and longitude values must be in degrees for both index and query
points.

See https://github.com/benbovy/pys2index.



This index adapter is registered in xoak under the name ``s2point``.
You can use it in :meth:`xarray.Dataset.xoak.set_index` by simply providing
its name for the ``index_type`` argument.
Alternatively, you can access it via the index registry, i.e.,

>>> import xoak
>>> ireg = xoak.IndexRegistry()
>>> ireg.s2point
File:           ~/Git/github/benbovy/xoak/src/xoak/index/s2_adapters.py
Type:           ABCMeta
Subclasses: 
```

**Comment by benbovy** [comment]
I have no idea on what is causing random crashes on ubuntu...

**Comment by benbovy** [comment]
Mmm looks like `pys2index` conda packages might be broken on GH-actions `ubuntu-latest` (that's surprising since the feedstock built fine on conda-forge CI)...

**Comment by benbovy** [comment]
I'm going to merge this and move on with the remaining items in #29. Thanks @willirath for having a look!

**Pull request merged**
