### PR TITLE
Re-enable tests with pys2index on Linux

### PR DESCRIPTION
**Pull request by benbovy**
The `pys2index` conda-forge packages have been rebuilt in https://github.com/conda-forge/pys2index-feedstock/pull/1.

### CODE REVIEW

**Comment by benbovy** [comment]
Mmm so the problem is not solved by the freshly built conda-forge packages. Even worse, `pys2index` is broken for Python 3.9 on all platforms (see https://github.com/benbovy/pys2index/pull/3). No idea (yet) why...

**Comment by benbovy** [comment]
`pys2index` has been fixed in the last release.

I also removed python 3.6 from the test matrix. Seg faults happen for that version now, which is caused by `pys2index` too. But I prefer seg faults happening with Python 3.6 rather than with Python 3.9. And since numpy 1.20 has dropped support for Python 3.6, I think it is ok to do the same here too.

**Comment by willirath** [comment]
Is this ready for merging? (Looks good from my point of view.)

**Comment by benbovy** [comment]
Yes it's ready!

**Pull request merged**
